sudo: required
language: python
python:
- 3.6
services:
- docker
env:
  global:
  - DOCKER_USERNAME=alexlloyd
  - secure: WRkq98PbJe1gnivPO6291sKe+7fphn+B/+9XakTNvwg27v1Cnb7RjxERGtyYkduXgu8cMDcnqmYw3nDtsW5ixI6A3hoar1okO05HEiCBEjrJmzeARfMRTEK/b0Ct4bz2YzlV+rV3+7GgL+3gWPPptaDtyHiS0xXQKWfgBfVkcoYoKUu8UDrBseGYJoCdxvr9jqwAOaj1t4C6x7AheLIMYZKJ5gUT4IIiKY6C6iFk7dZsVmvnfDg0R7ZOH/41aDP05sjCX4DsslLqIkcN7Ru4GiuxqHA19wOYQKegLTJMWtMhmRRLS3rRUWrDG10czb9rEuPIYweFYMwhbtVXcVYqeec3CEJvm9/XGMrBsxZj82D1VeJXB51GOtWgkRLAARULZxjXxJtXvQxiUdeYH2Y5QsJCg2yuRoxyTQyjG51s7WxFZNMlaZEKnCsSjUXsSLrHwZujUN65ZUsqPj03clxbgzPfsl2kAn4RjytbjmLFZ2s7mLilyMiyt17K/7qfYxrTE412rBrr+AW6uLok/n56fkobdqsrFaEp1TZA/VvQoREBF453e1v2rSGO0PSHi5tVTgYRLn7lok9znV4CSWHzYiaflVxgWxhw/BOhIKWM6jKjp2eJ5KI/naDVtknkD7c2r+/BOrEgJgWlKX+IjOVb7/50GE/ubvtyc9YYcpMwvaU=
  - secure: saw7TPyU2QzXM6qROldkaWYK3YsJQL9HGlYfVhGIWO4pOaG2L/2t7hJn6BBTN9Ap5XmhANzTySizd2Po9OpkmtiEB9o5MPyat6gBOoBFJgM8XitUzZVYnOuF3X/vpLoPqccNfStuVUtB7AkpONHrJalQpRntA0XuqY23FfaLd2PaoMaUmZ8dYq3T6RVewgAoHACQYEg6zsQVTqDgU3AWXKUakTZ8Ji6k1NxG1kObrQVyB/5m/a/QIqVIzfIqCak2w+zaiBdTbeNKM/9F4JLvYFV/Ya9+Y6DS8DAjL43cy+rUs5twsyOGCzY//lJ90PDBAZcuBEebFrUeU5BH5Ptg9LwDHxRZkeAEIcOxqS8ok2PrwgWsFr6nFXNm11j1hOHnjcw/V7cx1BFpvVPBGsmJhPw4VFQvQLkCvIqmDcS+ZlDof4l2ko/8gK/1WW1eO+x/lAxVw/N5bCelpNa+l4s7k7xqfzPnJcAf6S4hRRxkOyEO8O26pYFD4e8ZhV+Yt6Py62DKMZML/z+jhmZG63A+hBkAeel35FDMZhk6nfkC0dGwGJcviTmKli2Ylq08BY/i3o/laDn0OI3fm3sSJTgtS994uZ/JS/cn383PkLhT/WY44NGMT7+7d44XdB+rdmlpi0yQ/MPTtGYd3Qp6nNWaI04+YSMY9I03APhLRjX4gfs=
install:
- pip install pycodestyle mypy
before_script:
- echo $DOCKER_PASSWORD
- pycodestyle
- mypy run.py pointy --ignore-missing-imports
script:
- docker build --tag pointy:$TRAVIS_BRANCH .
after_success:
- docker run -d pointy:$TRAVIS_BRANCH -e POINTY_VERIFY_TOKEN
deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push
  on:
    branch: linode
    tags: true
