version: 1
disable_existing_loggers: False
formatters:
    screen:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"


handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: screen
        stream: ext://sys.stdout

root:
    level: DEBUG
    handlers: [console]